# Generated by Django 5.2.7 on 2026-01-25 23:50

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('flights', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('passenger_name', models.CharField(help_text='Full name of the passenger', max_length=200)),
                ('passenger_email', models.EmailField(help_text='Contact email for booking confirmation', max_length=254)),
                ('seats_booked', models.PositiveIntegerField(default=1, help_text='Number of seats reserved in this booking', validators=[django.core.validators.MinValueValidator(1)])),
                ('total_price', models.DecimalField(decimal_places=2, help_text='Total cost (seats_booked × flight.price)', max_digits=10, validators=[django.core.validators.MinValueValidator(0.01)])),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('cancelled', 'Cancelled')], default='pending', help_text='Current status of the booking', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When the booking was initially created')),
                ('confirmed_at', models.DateTimeField(blank=True, help_text='When the booking was confirmed', null=True)),
                ('cancelled_at', models.DateTimeField(blank=True, help_text='When the booking was cancelled (if applicable)', null=True)),
                ('special_requests', models.TextField(blank=True, help_text='Any special requirements or requests', max_length=500)),
                ('flight', models.ForeignKey(help_text='The flight being booked', on_delete=django.db.models.deletion.PROTECT, related_name='bookings', to='flights.flight')),
            ],
            options={
                'verbose_name': 'Booking',
                'verbose_name_plural': 'Bookings',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['passenger_email'], name='booking_boo_passeng_3e1e3e_idx'), models.Index(fields=['status', 'created_at'], name='booking_boo_status_4662db_idx'), models.Index(fields=['flight', 'status'], name='booking_boo_flight__3a8db0_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('seats_booked__gt', 0)), name='positive_seats_booked'), models.CheckConstraint(condition=models.Q(('total_price__gte', 0.01)), name='positive_total_price')],
            },
        ),
    ]
