# Generated by Django 5.2.7 on 2026-01-25 23:50

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Flight',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flight_number', models.CharField(help_text='Unique flight identifier (e.g., AA123, DL456)', max_length=10, unique=True)),
                ('airline', models.CharField(help_text='Airline operating the flight', max_length=100)),
                ('departure_city', models.CharField(help_text='City where the flight departs from', max_length=100)),
                ('arrival_city', models.CharField(help_text='City where the flight arrives at', max_length=100)),
                ('departure_time', models.DateTimeField(help_text='Scheduled departure date and time (local time)')),
                ('arrival_time', models.DateTimeField(help_text='Scheduled arrival date and time (local time)')),
                ('total_seats', models.PositiveIntegerField(help_text='Total number of seats on the aircraft', validators=[django.core.validators.MinValueValidator(1)])),
                ('available_seats', models.PositiveIntegerField(help_text='Number of seats currently available for booking')),
                ('price', models.DecimalField(decimal_places=2, help_text='Price per seat in USD', max_digits=10, validators=[django.core.validators.MinValueValidator(0.01)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Flight',
                'verbose_name_plural': 'Flights',
                'ordering': ['departure_time'],
                'indexes': [models.Index(fields=['departure_city', 'arrival_city'], name='flights_fli_departu_5c22ea_idx'), models.Index(fields=['departure_time'], name='flights_fli_departu_5bc2af_idx'), models.Index(fields=['price'], name='flights_fli_price_59fecb_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('departure_time__lt', models.F('arrival_time'))), name='departure_before_arrival'), models.CheckConstraint(condition=models.Q(('available_seats__lte', models.F('total_seats'))), name='available_seats_lte_total_seats'), models.CheckConstraint(condition=models.Q(('price__gte', 0.01)), name='price_positive')],
            },
        ),
    ]
