# Generated by Django 5.2.7 on 2026-02-23 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='flight',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
